version: '3'

services:
  app-development:
    image: registry.gitlab.com/mulailomba/mla-backend:latest
    networks:
      - nginx
    env_file:
      - .env
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
networks:
  nginx:
    external: true
