version: '3'

services:
  api:
    image: registry.gitlab.com/mulailomba/mla-backend:latest
    env_file:
      - .env
    ports:
      - '8100-8102:8000'
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: always
