export enum EVENT_TIMELINE_TYPE {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  INFORMATION = 'INFORMATION',
}

export enum EVENT_ADDITIONAL_INPUT_TYPE {
  INPUT = 'INPUT',
  FILE = 'FILE',
  TEXT_AREA = 'TEXT_AREA',
  MULTIPLE = 'MULTIPLE',
  SINGLE = 'SINGLE',
}

export const CREATE_EVENT_UNIT_OF_WORK_FACTORY = 'CREATE_EVENT_UNIT_OF_WORK_FACTORY';
