export enum EVENT_TIMELINE_TYPE_ENUM {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  INFORMATION = 'INFORMATION',
}

export enum EVENT_PREREQUISITE_TYPE_ENUM {
  INPUT = 'INPUT',
  FILE = 'FILE',
  TEXT_AREA = 'TEXT_AREA',
  MULTIPLE = 'MULTIPLE',
  SINGLE = 'SINGLE',
}

export enum EVENT_CATEGORY_STATUS_ENUM {
  DRAFT = 'DRAFT',
  UPCOMING = 'UPCOMING',
  PUBLISHED = 'PUBLISHED',
  ONGOING = 'ONGOING',
  FINISHED = 'FINISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum EVENT_ELIGIBILITY_ENUM {
  SD = 'SD',
  SMP = 'SMP',
  SMA = 'SMA',
  MAHASISWA = 'MAHASISWA',
  UMUM = 'UMUM',
}

export const CREATE_EVENT_UNIT_OF_WORK_FACTORY = 'CREATE_EVENT_UNIT_OF_WORK_FACTORY';
export const EVENT_READ_REPOSITORY = 'EVENT_READ_REPOSITORY';
export const EVENT_WRITE_REPOSITORY = 'EVENT_WRITE_REPOSITORY';
export const EVENT_CATEGORY_WRITE_REPOSITORY = 'EVENT_CATEGORY_WRITE_REPOSITORY';
