export const CategoryFactory = [
  { description: 'Animasi 2D', name: 'animasi_2d' },
  { description: 'Animasi 3D', name: 'animasi_3d' },
  { description: 'Bisnis dan Manajemen', name: 'bisnis_dan_manajemen' },
  { description: 'Desain Exterior', name: 'desain_exterior' },
  { description: 'Desain Grafis', name: 'desain_grafis' },
  { description: 'Desain Interior', name: 'desain_interior' },
  { description: 'Esport game', name: 'esport_game' },
  { description: 'Fashion dan Busana', name: 'fashion_dan_busana' },
  { description: 'Festival Sastra', name: 'festival_sastra' },
  { description: 'Fotografi', name: 'fotografi' },
  { description: 'Inovasi', name: 'inovasi' },
  { description: 'Inovasi Pembelajaran', name: 'inovasi_pembelajaran' },
  { description: 'Kecantikan dan Perawatan Diri', name: 'kecantikan_dan_perawatan_diri' },
  { description: 'Kecerdasan Buatan', name: 'kecerdasan_buatan' },
  { description: 'Kebudayaan', name: 'kebudayaan' },
  { description: 'Keagamaan', name: 'keagamaan' },
  { description: 'Kepemimpinan', name: 'kepemimpinan' },
  { description: 'Kesehatan', name: 'kesehatan' },
  { description: 'Kewirausahaan', name: 'kewirausahaan' },
  { description: 'Kompetisi Debat', name: 'kompetisi_debat' },
  { description: 'Kompetisi E-Learning', name: 'kompetisi_e_learning' },
  { description: 'Kompetisi Film Pendidikan', name: 'kompetisi_film_pendidikan' },
  { description: 'Kompetisi Gamifikasi Pendidikan', name: 'kompetisi_gamifikasi_pendidikan' },
  { description: 'Kompetisi Media Pembelajaran', name: 'kompetisi_media_pembelajaran' },
  { description: 'Kompetisi Penulisan Puisi', name: 'kompetisi_penulisan_puisi' },
  { description: 'Kompetisi Seni Budaya', name: 'kompetisi_seni_budaya' },
  { description: 'Lomba Baca Puisi', name: 'lomba_baca_puisi' },
  { description: 'Lomba Blog Pendidikan', name: 'lomba_blog_pendidikan' },
  { description: 'Lomba Cerdas Cermat', name: 'lomba_cerdas_cermat' },
  { description: 'Lomba Debat Ilmiah', name: 'lomba_debat_ilmiah' },
  { description: 'Lomba Desain Pendidikan', name: 'lomba_desain_pendidikan' },
  { description: 'Lomba Inovasi Pendidikan', name: 'lomba_inovasi_pendidikan' },
  { description: 'Lomba Karya Seni Digital', name: 'lomba_karya_seni_digital' },
  { description: 'Lomba Karya Seni Sekolah', name: 'lomba_karya_seni_sekolah' },
  { description: 'Lomba Literasi Pendidikan', name: 'lomba_literasi_pendidikan' },
  { description: 'Lomba Mading Sekolah', name: 'lomba_mading_sekolah' },
  { description: 'Lomba Matematika Online', name: 'lomba_matematika_online' },
  { description: 'Lomba Penelitian Sains', name: 'lomba_penelitian_sains' },
  { description: 'Lomba Penelitian Sosial', name: 'lomba_penelitian_sosial' },
  { description: 'Lomba Pembelajaran Berbasis Proyek', name: 'lomba_pembelajaran_berbasis_proyek' },
  { description: 'Lomba Pendidikan Anak Usia Dini', name: 'lomba_pendidikan_anak_usia_dini' },
  { description: 'Lomba Pendidikan Karakter', name: 'lomba_pendidikan_karakter' },
  { description: 'Lomba Pendidikan Lingkungan', name: 'lomba_pendidikan_lingkungan' },
  { description: 'Lomba Penulisan Esai', name: 'lomba_penulisan_esai' },
  { description: 'Lomba Perancangan Kurikulum', name: 'lomba_perancangan_kurikulum' },
  { description: 'Lomba Pidato', name: 'lomba_pidato' },
  { description: 'Lomba Presentasi Proyek', name: 'lomba_presentasi_proyek' },
  { description: 'Lomba Rancang Bangun Alat', name: 'lomba_rancang_bangun_alat' },
  { description: 'Lomba Teater Pendidikan', name: 'lomba_teater_pendidikan' },
  { description: 'Lomba Video Edukatif', name: 'lomba_video_edukatif' },
  { description: 'Olahraga', name: 'olahraga' },
  { description: 'Olimpiade Astronomi', name: 'olimpiade_astronomi' },
  { description: 'Olimpiade Bahasa Arab', name: 'olimpiade_bahasa_arab' },
  { description: 'Olimpiade Bahasa Daerah', name: 'olimpiade_bahasa_daerah' },
  { description: 'Olimpiade Bahasa Inggris', name: 'olimpiade_bahasa_inggris' },
  { description: 'Olimpiade Bahasa Jepang', name: 'olimpiade_bahasa_jepang' },
  { description: 'Olimpiade Bahasa Mandarin', name: 'olimpiade_bahasa_mandarin' },
  { description: 'Olimpiade Bahasa Perancis', name: 'olimpiade_bahasa_perancis' },
  { description: 'Olimpiade Bahasa Spanyol', name: 'olimpiade_bahasa_spanyol' },
  { description: 'Olimpiade Biologi', name: 'olimpiade_biologi' },
  { description: 'Olimpiade Fisika', name: 'olimpiade_fisika' },
  { description: 'Olimpiade Geografi', name: 'olimpiade_geografi' },
  { description: 'Olimpiade IPS', name: 'olimpiade_ips' },
  { description: 'Olimpiade IPA', name: 'olimpiade_ipa' },
  { description: 'Olimpiade Kimia', name: 'olimpiade_kimia' },
  { description: 'Olimpiade Kewirausahaan', name: 'olimpiade_kewirausahaan' },
  { description: 'Olimpiade Matematika', name: 'olimpiade_matematika' },
  { description: 'Olimpiade Sains dan Teknologi', name: 'olimpiade_sains_dan_teknologi' },
  { description: 'Olimpiade Sejarah', name: 'olimpiade_sejarah' },
  { description: 'Olimpiade TIK', name: 'olimpiade_tik' },
  { description: 'Pendidikan', name: 'pendidikan' },
  { description: 'Pengembangan Aplikasi', name: 'pengembangan_aplikasi' },
  { description: 'Pengembangan Web', name: 'pengembangan_web' },
  { description: 'Robotika', name: 'robotika' },
  { description: 'Sastra dan Bahasa', name: 'sastra_dan_bahasa' },
  { description: 'Seni Digital', name: 'seni_digital' },
  { description: 'Seni Kreatif', name: 'seni_kreatif' },
  { description: 'Seni Rupa', name: 'seni_rupa' },
  { description: 'Teknologi', name: 'teknologi' },
  { description: 'Teknologi Informasi', name: 'teknologi_informasi' },
];
